// This file was generated by counterfeiter
package fake_controllers

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"github.com/jianqiu/vm-pool-server/handlers"
	"github.com/jianqiu/vm-pool-server/models"
)

type FakeVirtualGuestController struct {
	VirtualGuestsStub        func(logger lager.Logger, publicVlan, privateVlan, cpu, memory_mb int32) ([]*models.VirtualGuest, error)
	virtualGuestsMutex       sync.RWMutex
	virtualGuestsArgsForCall []struct {
		logger      lager.Logger
		publicVlan  int32
		privateVlan int32
		cpu         int32
		memory_mb   int32
	}
	virtualGuestsReturns struct {
		result1 []*models.VirtualGuest
		result2 error
	}
	VirtualGuestByCidStub        func(logger lager.Logger, cid int32) (*models.VirtualGuest, error)
	virtualGuestByCidMutex       sync.RWMutex
	virtualGuestByCidArgsForCall []struct {
		logger lager.Logger
		cid    int32
	}
	virtualGuestByCidReturns struct {
		result1 *models.VirtualGuest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVirtualGuestController) VirtualGuests(logger lager.Logger, publicVlan int32, privateVlan int32, cpu int32, memory_mb int32) ([]*models.VirtualGuest, error) {
	fake.virtualGuestsMutex.Lock()
	fake.virtualGuestsArgsForCall = append(fake.virtualGuestsArgsForCall, struct {
		logger      lager.Logger
		publicVlan  int32
		privateVlan int32
		cpu         int32
		memory_mb   int32
	}{logger, publicVlan, privateVlan, cpu, memory_mb})
	fake.recordInvocation("VirtualGuests", []interface{}{logger, publicVlan, privateVlan, cpu, memory_mb})
	fake.virtualGuestsMutex.Unlock()
	if fake.VirtualGuestsStub != nil {
		return fake.VirtualGuestsStub(logger, publicVlan, privateVlan, cpu, memory_mb)
	} else {
		return fake.virtualGuestsReturns.result1, fake.virtualGuestsReturns.result2
	}
}

func (fake *FakeVirtualGuestController) VirtualGuestsCallCount() int {
	fake.virtualGuestsMutex.RLock()
	defer fake.virtualGuestsMutex.RUnlock()
	return len(fake.virtualGuestsArgsForCall)
}

func (fake *FakeVirtualGuestController) VirtualGuestsArgsForCall(i int) (lager.Logger, int32, int32, int32, int32) {
	fake.virtualGuestsMutex.RLock()
	defer fake.virtualGuestsMutex.RUnlock()
	return fake.virtualGuestsArgsForCall[i].logger, fake.virtualGuestsArgsForCall[i].publicVlan, fake.virtualGuestsArgsForCall[i].privateVlan, fake.virtualGuestsArgsForCall[i].cpu, fake.virtualGuestsArgsForCall[i].memory_mb
}

func (fake *FakeVirtualGuestController) VirtualGuestsReturns(result1 []*models.VirtualGuest, result2 error) {
	fake.VirtualGuestsStub = nil
	fake.virtualGuestsReturns = struct {
		result1 []*models.VirtualGuest
		result2 error
	}{result1, result2}
}

func (fake *FakeVirtualGuestController) VirtualGuestByCid(logger lager.Logger, cid int32) (*models.VirtualGuest, error) {
	fake.virtualGuestByCidMutex.Lock()
	fake.virtualGuestByCidArgsForCall = append(fake.virtualGuestByCidArgsForCall, struct {
		logger lager.Logger
		cid    int32
	}{logger, cid})
	fake.recordInvocation("VirtualGuestByCid", []interface{}{logger, cid})
	fake.virtualGuestByCidMutex.Unlock()
	if fake.VirtualGuestByCidStub != nil {
		return fake.VirtualGuestByCidStub(logger, cid)
	} else {
		return fake.virtualGuestByCidReturns.result1, fake.virtualGuestByCidReturns.result2
	}
}

func (fake *FakeVirtualGuestController) VirtualGuestByCidCallCount() int {
	fake.virtualGuestByCidMutex.RLock()
	defer fake.virtualGuestByCidMutex.RUnlock()
	return len(fake.virtualGuestByCidArgsForCall)
}

func (fake *FakeVirtualGuestController) VirtualGuestByCidArgsForCall(i int) (lager.Logger, int32) {
	fake.virtualGuestByCidMutex.RLock()
	defer fake.virtualGuestByCidMutex.RUnlock()
	return fake.virtualGuestByCidArgsForCall[i].logger, fake.virtualGuestByCidArgsForCall[i].cid
}

func (fake *FakeVirtualGuestController) VirtualGuestByCidReturns(result1 *models.VirtualGuest, result2 error) {
	fake.VirtualGuestByCidStub = nil
	fake.virtualGuestByCidReturns = struct {
		result1 *models.VirtualGuest
		result2 error
	}{result1, result2}
}

func (fake *FakeVirtualGuestController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.virtualGuestsMutex.RLock()
	defer fake.virtualGuestsMutex.RUnlock()
	fake.virtualGuestByCidMutex.RLock()
	defer fake.virtualGuestByCidMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeVirtualGuestController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.VirtualGuestController = new(FakeVirtualGuestController)
