package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// VM VM
// swagger:model VM
type VM struct {

	// cpu core
	CPU int32 `json:"cpu,omitempty"`

	// The name of the deployment the VM belongs to
	Deployment string `json:"deployment,omitempty"`

	// hostname of VM
	Hostname string `json:"hostname,omitempty"`

	// Memory size
	Memory int32 `json:"memory,omitempty"`

	// Private IP
	PrivateIP string `json:"private_ip,omitempty"`

	// PrimaryBackendNetworkVlan
	PrivateVlan int32 `json:"private_vlan,omitempty"`

	// PrimaryNetworkVlan
	PublicVlan int32 `json:"public_vlan,omitempty"`

	// Status of VM in Pool
	Status string `json:"status,omitempty"`

	// VM id
	VMID int32 `json:"vm_id,omitempty"`
}

// Validate validates this VM
func (m *VM) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
