package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// VMID VM ID
// swagger:model VMID
type VMID int32

// Validate validates this VM ID
func (m VMID) Validate(formats strfmt.Registry) error {
	return nil
}
