package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// VMID VM ID
// swagger:model VMID
type VMID struct {

	// VM id
	VMID int32 `json:"vm_id,omitempty"`
}

// Validate validates this VM ID
func (m *VMID) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
