// Code generated by protoc-gen-go.
// source: vm_requests.proto
// DO NOT EDIT!

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	vm_requests.proto

It has these top-level messages:
	VMLifecycleResponse
	VMsRequest
	VMsResponse
	VMByCidRequest
	VMResponse
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VMLifecycleResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *VMLifecycleResponse) Reset()                    { *m = VMLifecycleResponse{} }
func (m *VMLifecycleResponse) String() string            { return proto.CompactTextString(m) }
func (*VMLifecycleResponse) ProtoMessage()               {}
func (*VMLifecycleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VMLifecycleResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VMsRequest struct {
	PublicVlan  int32 `protobuf:"varint,1,opt,name=public_vlan,json=publicVlan" json:"public_vlan,omitempty"`
	PrivateVlan int32 `protobuf:"varint,2,opt,name=private_vlan,json=privateVlan" json:"private_vlan,omitempty"`
	Cpu         int32 `protobuf:"varint,3,opt,name=cpu" json:"cpu,omitempty"`
	MemoryMb    int32 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb" json:"memory_mb,omitempty"`
}

func (m *VMsRequest) Reset()                    { *m = VMsRequest{} }
func (m *VMsRequest) String() string            { return proto.CompactTextString(m) }
func (*VMsRequest) ProtoMessage()               {}
func (*VMsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VMsResponse struct {
	Error *Error        `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Vms   *VirtualGuest `protobuf:"bytes,2,opt,name=vms" json:"vms,omitempty"`
}

func (m *VMsResponse) Reset()                    { *m = VMsResponse{} }
func (m *VMsResponse) String() string            { return proto.CompactTextString(m) }
func (*VMsResponse) ProtoMessage()               {}
func (*VMsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VMsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *VMsResponse) GetVms() *VirtualGuest {
	if m != nil {
		return m.Vms
	}
	return nil
}

type VMByCidRequest struct {
	Cid string `protobuf:"bytes,1,opt,name=cid" json:"cid,omitempty"`
}

func (m *VMByCidRequest) Reset()                    { *m = VMByCidRequest{} }
func (m *VMByCidRequest) String() string            { return proto.CompactTextString(m) }
func (*VMByCidRequest) ProtoMessage()               {}
func (*VMByCidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type VMResponse struct {
	Error *Error        `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Vm    *VirtualGuest `protobuf:"bytes,2,opt,name=vm" json:"vm,omitempty"`
}

func (m *VMResponse) Reset()                    { *m = VMResponse{} }
func (m *VMResponse) String() string            { return proto.CompactTextString(m) }
func (*VMResponse) ProtoMessage()               {}
func (*VMResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VMResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *VMResponse) GetVm() *VirtualGuest {
	if m != nil {
		return m.Vm
	}
	return nil
}

func init() {
	proto.RegisterType((*VMLifecycleResponse)(nil), "models.VMLifecycleResponse")
	proto.RegisterType((*VMsRequest)(nil), "models.VMsRequest")
	proto.RegisterType((*VMsResponse)(nil), "models.VMsResponse")
	proto.RegisterType((*VMByCidRequest)(nil), "models.VMByCidRequest")
	proto.RegisterType((*VMResponse)(nil), "models.VMResponse")
}

func init() { proto.RegisterFile("vm_requests.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xd5, 0x86, 0x56, 0xf4, 0x0c, 0x08, 0x5c, 0x86, 0xa8, 0x0c, 0x80, 0x41, 0x88, 0x29,
	0x43, 0xd9, 0x18, 0x41, 0x88, 0x85, 0x2c, 0x1e, 0x82, 0xc4, 0x12, 0xe5, 0x8f, 0x41, 0x96, 0xec,
	0x38, 0xd8, 0x89, 0xa5, 0x4c, 0x7c, 0x75, 0xe4, 0x33, 0x5d, 0x91, 0xba, 0x5d, 0xde, 0xfb, 0xe5,
	0xde, 0xdd, 0x19, 0xce, 0xbc, 0x2e, 0xad, 0xf8, 0x1e, 0x85, 0x1b, 0x5c, 0xd6, 0x5b, 0x33, 0x18,
	0xba, 0xd4, 0xa6, 0x15, 0xca, 0x6d, 0xd6, 0x5e, 0xda, 0x61, 0xac, 0x54, 0xf9, 0x15, 0xdc, 0x68,
	0x6e, 0x88, 0xb0, 0xd6, 0xd8, 0xf8, 0xc1, 0x1e, 0x61, 0x5d, 0xe4, 0x6f, 0xf2, 0x53, 0x34, 0x53,
	0xa3, 0x04, 0x17, 0xae, 0x37, 0x9d, 0x13, 0xf4, 0x06, 0x16, 0x48, 0xa5, 0xb3, 0xab, 0xd9, 0x3d,
	0xd9, 0x1e, 0x67, 0xb1, 0x61, 0xf6, 0x12, 0x44, 0x1e, 0x3d, 0xf6, 0x03, 0x50, 0xe4, 0x8e, 0xc7,
	0x68, 0x7a, 0x09, 0xa4, 0x1f, 0x6b, 0x25, 0x9b, 0xd2, 0xab, 0xaa, 0xc3, 0x1f, 0x17, 0x1c, 0xa2,
	0x54, 0xa8, 0xaa, 0xa3, 0xd7, 0x70, 0xd4, 0x5b, 0xe9, 0xab, 0x41, 0x44, 0x62, 0x8e, 0x04, 0xf9,
	0xd3, 0x10, 0x39, 0x85, 0xa4, 0xe9, 0xc7, 0x34, 0x41, 0x27, 0x94, 0xf4, 0x02, 0x56, 0x5a, 0x68,
	0x63, 0xa7, 0x52, 0xd7, 0xe9, 0x01, 0xea, 0x87, 0x51, 0xc8, 0x6b, 0xf6, 0x01, 0x04, 0x07, 0xd8,
	0x63, 0x68, 0x7a, 0x07, 0x89, 0xd7, 0x0e, 0xc3, 0xc9, 0xf6, 0x7c, 0x87, 0x14, 0xf1, 0x4e, 0xaf,
	0x61, 0x13, 0x1e, 0x00, 0xc6, 0xe0, 0xa4, 0xc8, 0x9f, 0xa6, 0x67, 0xd9, 0xee, 0x16, 0x0c, 0xc3,
	0xc9, 0x16, 0x9b, 0xaf, 0x78, 0x28, 0xd9, 0x7b, 0x38, 0xc0, 0x7e, 0xf1, 0xb7, 0x30, 0xf7, 0xfa,
	0xdf, 0xf4, 0xb9, 0xd7, 0xf5, 0x12, 0x1f, 0xe7, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x67,
	0xf8, 0xed, 0xdb, 0x01, 0x00, 0x00,
}
